SYMBOLS = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'META', 'AMD', 'INTC', 'SPY', 'QQQ']

# Medium-sized list of symbols (50)
MED_SYMBOLS = ['AAPL', 'ABNB', 'ADBE', 'ADI', 'ADP', 'ADSK', 'AMAT', 'AMD', 'AMGN', 'AMZN', 'ASML',
               'AVGO', 'BKNG', 'CDNS', 'CMCSA', 'COST', 'CSCO', 'GOOG', 'GOOGL', 'INTC', 'F',
               'INTU', 'ISRG', 'LRCX', 'MELI', 'META', 'MSFT', 'NFLX', 'NVDA', 'PYPL', 'QCOM', 'LCID',
               'DUK', 'MMM', 'SBUX', 'TXN', 'TSLA', 'SPY', 'QQQ', 'AIG', 'NIO', 'PLTR', 'QBTS', 'IQ',
               'SNAP', 'SMCI', 'NU', 'TSM', 'BABA', 'BMY', 'LPSN']

LARGE_SYMBOLS = ['AAPL', 'ABNB', 'ADBE', 'ADI', 'ADP', 'ADSK', 'AMAT', 'AMD', 'AMGN', 'AMZN', 'ASML',
                 'AVGO', 'BKNG', 'CDNS', 'CMCSA', 'COST', 'CSCO', 'GOOG', 'GOOGL', 'INTC', 'F',
                 'INTU', 'ISRG', 'LRCX', 'MELI', 'META', 'MSFT', 'NFLX', 'NVDA', 'PYPL', 'QCOM', 'LCID',
                 'DUK', 'MMM', 'SBUX', 'TXN', 'TSLA', 'SPY', 'QQQ', 'AIG', 'NIO', 'PLTR', 'QBTS', 'IQ',
                 'SNAP', 'SMCI', 'NU', 'TSM', 'BABA', 'BMY', 'LPSN', 'TMUS', 'CRWD', 'ZM', 'ROKU', 'MTCH',
                 'OKTA', 'ZS', 'DDOG', 'NET', 'MDB', 'DOCU', 'PDD', 'JD', 'BILI', 'BIDU', 'NTES',
                 'WDAY', 'TWLO', 'TEAM', 'CRM', 'NOW', 'TTD', 'PINS', 'ETSY', 'SPOT', 'DASH', 'RIVN',
                 'RBLX', 'U', 'COIN', 'SNOW', 'SHOP', 'UBER', 'LYFT', 'PTON', 'CHWY', 'ZI', 'DT', 'DKNG',
                 'CRSR', 'HOOD', 'SOFI', 'AFRM', 'UPST', 'FUBO', 'WISH', 'ROOT', 'CLOV', 'ME', 'OPEN',
                 'MILE', 'OSCR', 'PATH', 'IONQ', 'DNA', 'ENVX', 'LAC', 'MP', 'LAZR', 'CHPT', 'BLNK',
                 'FCEL', 'PLUG', 'BE', 'ENPH', 'SEDG', 'RUN', 'NOVA', 'SHLS', 'FSLR', 'LI', 'XPEV',
                 'FFIE', 'FSR', 'GOEV', 'NKLA', 'WKHS', 'RIDE', 'HYLN', 'ARVL', 'PTRA', 'VLD', 'DM',
                 'MKFG', 'XMTR', 'CFLT', 'GLBE', 'GTLB', 'ASAN', 'MNDY', 'AI', 'CRDO', 'WRBY', 'DOCS',
                 'BZFD', 'SMRT', 'BIRD', 'OUST', 'APPH', 'JOBY', 'LILM', 'ACHR', 'EVGO', 'DCFC', 'SLDP',
                 'QS', 'STEM', 'GEVO', 'CLNE', 'MARA', 'RIOT', 'CIFR', 'HUT', 'BTBT', 'BITF', 'BITO',
                 'GBTC', 'ETHE', 'SGMO', 'CRSP', 'EDIT', 'NTLA', 'BEAM', 'VERV', 'VCYT', 'EXAS', 'PACB',
                 'BNGO', 'RXRX', 'FATE', 'TWST', 'ABCL', 'GDRX', 'CERT', 'ACVA', 'COUR', 'DUOL',
                 'HIMS', 'ELAN', 'ALEC', 'SANA', 'SRNE', 'NVAX', 'MRNA', 'BNTX', 'VXRT', 'OCGN', 'INO',
                 'GERN', 'GRTS', 'CMRX', 'SAVA', 'CRNC', 'CRNX', 'ARGX', 'KRYS', 'NARI',
                 'TVTX', 'AVXL', 'AXSM', 'IONS', 'JAZZ', 'SAGE', 'ACAD', 'VTRS', 'ZTS', 'VRTX',
                 'REGN', 'ALNY', 'ILMN', 'BIIB', 'GILD', 'IDXX', 'DXCM', 'ALGN', 'VEEV', 'HOLX', 'EXEL',
                 'BMRN', 'UTHR', 'RGEN', 'NBIX', 'TECH', 'ICLR', 'BHC', 'XRAY',
                 'TGTX', 'FOLD', 'DVAX', 'RARE', 'CDXS', 'ITCI', 'RCUS', 'NTRA', 'CRBU', 'GTHX', 'LCTX',
                 'STRO', 'MGNX', 'KURA', 'KYMR', 'DNAY', 'ATRA', 'LYEL', 'CERE', 'CNTA', 'OMGA', 'TSVT',
                 'CERE', 'NOTV', 'PRCT', 'RXST', 'ITOS', 'BDTX', 'LUNG', 'PROC', 'ALLK', 'IMVT', 'RAPT',
                 'ABUS', 'AFMD', 'CARA', 'GRCL', 'MORF', 'ANNX', 'TCRR', 'KNTE', 'CCCC', 'TALS', 'TSHA',
                 'DCPH', 'HGEN', 'PRTA', 'GLPG', 'GMAB', 'BPMC', 'KRTX', 'ATRC', 'NSTG', 'QDEL', 'NVTS',
                 'RPAY', 'SEAC', 'CARG', 'EGHT', 'ALTR', 'QLYS', 'SAIL', 'APPS', 'BAND', 'BIGC',
                 'BLKB', 'CCOI', 'CNXN', 'CSGS', 'CYBR', 'DBX', 'DOMO', 'DTSS',
                 'EBAY', 'EGRX', 'ELF', 'ELTK', 'ENLV',
                 'ENPH', 'ENTG', 'EPAM', 'EQIX', 'EQBK', 'ERIC', 'ESLT', 'ESTC', 'ETSY',
                 'EVRI', 'EXEL', 'EXLS', 'EXPE', 'EXPO', 'EXTR', 'FANG', 'FBIO', 'FBIZ',
                 'FBNC', 'FCBC', 'FCEL', 'FCFS', 'FCNCA', 'FCPT', 'FDBC', 'FDUS',
                 'FEIM', 'FELE', 'FFBC', 'FFIC', 'FFIN', 'FFIV', 'FFNW', 'FFWM', 'FGBI', 'FGEN',
                 'FHB', 'FIBK', 'FITB', 'FIVE', 'FIVN', 'FIZZ', 'FLGT', 'FLIC',
                 'FLNT', 'FLWS', 'FMBH', 'FMNB', 'FNKO', 'FNLC',
                 'FOLD', 'FORM', 'FORR', 'FOSL', 'FOX', 'FOXA', 'FOXF', 'FRBA',
                 'FRHC', 'FRME', 'FROG', 'FRPH', 'FRPT', 'FRSX', 'FSBW', 'FSEA', 'FSFG', 'FSLR',
                 'FTDR', 'FTEK', 'FTFT', 'FTGC', 'FTHI', 'FTNT', 'FTRI', 'FULT',
                 'FUNC', 'FUSB', 'FUTU', 'FWONA', 'FWONK', 'FWRD', 'FXNC', 'GABC',
                 'GAIA', 'GAIN', 'GAINL', 'GALT', 'GAME', 'GAN', 'GANX', 'GASS', 'GBCI', 'GBDC',
                 'GBIO', 'GCBC', 'GDEN', 'GDRX', 'GDS', 'GDYN', 'GECC',
                 'GEG', 'GENC', 'GENE', 'GEOS', 'GERN', 'GEVO', 'GGAL', 'GH', 'GHSI',
                 'GIFI', 'GIII', 'GILD', 'GILT', 'GLBS', 'GLBZ', 'GLDD', 'GLNG', 'GLPG', 'GLPI', 'GLRE',
                 'GLYC', 'GM', 'GME', 'GMHI', 'GMHIU', 'GMHIW', 'GMTX', 'GNCA', 'GNFT', 'GNLN', 'GNMA',
                 'GNMK', 'GNOM', 'GNTX', 'GNTY', 'GO', 'GOCO', 'GOGL', 'GOGO', 'GOOD', 'GOODM', 'GOODO',
                 'GOOG', 'GOOGL', 'GOSS', 'GOVX', 'GP', 'GPMT', 'GPP', 'GPRE', 'GPRO', 'GRAY', 'GRBK',
                 'GRCL', 'GRCY', 'GRCYU', 'GRCYW', 'GRFS', 'GRIN', 'GRPN', 'GRSV', 'GRSVU', 'GRSVW',
                 'GRTX', 'GRVY', 'GRWG', 'GSBC', 'GSHD', 'GSIT', 'GSKY', 'GSM', 'GSMG', 'GSMGW',
                 'GTBP', 'GTEC', 'GTH', 'GTIM', 'GTLS', 'GTLS', 'GTLS']